### ISSUE TITLE
Mobile apps

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#1803]
We could really use a hand at making this happen, there's quite a bit of ReactNative work to go yet. 

**If you're interested in helping out with mobile apps, please see the linked issue for the individual screens below!**

- ~~Shared component library built with `styled-components/primitives` (@brianlovin you had a WIP PR for this somewhere?)~~
- [x] Figure out if we want to use expo.io (probably?)
- [x] Set up repo architecture
- [x] Set up dev process for iOS and Android
- [x] Set up build process for iOS and Android
- [x] Decide on list of views to build for MVP
- [ ] Set up submission process to App Store and Play Store
- [ ] Build app
  - [x] Splash page, see #2329 
  - [x] Thread feeds, see #2330 
  - [x] Thread view, see #2331 
  - [ ] Notifications, see #2332 
  - [ ] Loading states (skeleton loaders like the website)
  - [ ] Null states for empty screens
  - [ ] Joining communities/channels from their profiles
  - [ ] New user onboarding (like on the website)

**Comment by juliankrispel** [comment]
@mxstbr so is there a branch for this?

**Comment by mxstbr** [comment]
Nope, all the WIP has been merged to `alpha`. Just continue working from there!

**Comment by juliankrispel** [comment]
@mxstbr what are the services required to run the mobile app successfully?

![image](https://user-images.githubusercontent.com/1188186/38556148-f33c67e2-3cc8-11e8-8eed-be93c35713af.png)

**Comment by mxstbr** [comment]
@juliankrispel hmm, should only require the API running at the same time. I think that bug exists right now, try commenting out L88-92 in `mobile/views/Notification.js`

**Comment by mxstbr** [comment]
@juliankrispel that bug was fixed in #2809, and then the follow-up PR #2823 fixes authentication on mobile. Sorry for the troubles here, if you use that branch you should be good to go!

**Comment by mxstbr** [comment]
I think our push notifications are working already, at least they should be—we just don't handle them yet if they come in while the app is open and don't render them properly! Ref #2332

**Comment by homanp** [comment]
Ah, ok. Misunderstood then. Again I would be glad to help you out with that as well. Do you have any specific documentation on how you want to handle the notifications?

**Comment by mxstbr** [comment]
@homanp moved to #2332

**Comment by fullstackguyhere** [comment]
Hey @mxstbr I am interested in helping out!
