### ISSUE TITLE
Going open source

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2592]
Making an issue here to start collecting the effort required to get us to open source-ability:

- [x] Add Danger (#2567)
  - [x] Enforce flow typing of new files
  - [x] Auto-labelling plugin for PRs ([`danger-plugin-labels`](https://github.com/withspectrum/danger-plugin-labels))
- [x] Add ESLint (#2590)
- [x] Add issue template (#2596)
- [x] Clean up labels
  - [x] Add `good first issue` label
  - [x] Add description to all labels
  - [x] Consolidate "bug" labels?
- [x] Clean up local app setup (#2597) 
  - [x] Figure out how to provide example secrets (https://spectrum.chat/thread/545e0aaf-3dfd-4fa3-8470-7299492c3177)
  - [ ] Maybe make sure it runs on Windows?
- [x] Clean up README (#2597)
  - [x] Set contribution expectations (http://artsy.github.io/blog/2016/01/13/OSS-Expectations/)
  - [x] Explain local app setup
- [x] Clean up excessive profanity from old issues/PRs
- [x] Make sure there are no secrets in our git history
- [x] Figure out licensing (#2623)
- [x] Create long-term roadmap in a milestone or project or something (#2622)
- [x] Create non-default channel in spectrum community to talk about code
- [x] Write blog post
- [x] Open source! :tada:

**Bonus**

- [x] Add Peril
  - [x] Auto-labelling plugin for issues (WIP: withspectrum/danger-plugin-labels#4)
  - [x] Auto-close issues that don't follow issue template (apart from us three)
- [x] Rename iris to api (#2661)
- [ ] Delete old `cacert` (now unused)
- [ ] Shared db queries

**Comment by mxstbr** [comment]
Done! :tada:

**Comment by mxstbr** [comment]
God dammit bot.
