### ISSUE TITLE
[Mobile v1] Thread: Make sure all possible states are covered

### ISSUE THREAD

**Issue by ryota-murakami** [withspectrum/spectrum#3150]
## overview
migrate from https://github.com/withspectrum/spectrum/pull/3148
refer original to https://github.com/withspectrum/spectrum/issues/2330

### Investigation Result

| Image           | status | mobile coverd  |  
|----------------|---------------|---------------|
| ![screen shot 2018-05-17 at 20 44 03](https://user-images.githubusercontent.com/5501268/40175450-1b868ab8-5a13-11e8-93de-91cc4990f141.png) | Pined  |  ✕ |
|  ![screen shot 2018-05-18 at 2 54 49](https://user-images.githubusercontent.com/5501268/40194951-01b3061e-5a47-11e8-86d6-4ab132349db7.png)  | Actived  | 🙆‍♂️  |
|  ![screen shot 2018-05-18 at 17 22 59](https://user-images.githubusercontent.com/5501268/40224126-32136be0-5ac0-11e8-9210-05f332d623ba.png)  | New Messages!  |  ✕  |
| ![screen shot 2018-05-18 at 2 58 12](https://user-images.githubusercontent.com/5501268/40195104-7c8b1d5e-5a47-11e8-9315-6b08b121f923.png) | New THREAD!  | 🙆‍♂️ |
| ![screen shot 2018-05-18 at 18 43 44](https://user-images.githubusercontent.com/5501268/40228157-740758bc-5acb-11e8-83f3-e26db350b816.png) | Locked  | ✕ |
| ![screen shot 2018-05-18 at 18 46 17](https://user-images.githubusercontent.com/5501268/40228274-cc8d5f68-5acb-11e8-812d-f8072fb5e65f.png) | Openchat  | ✕  |
| ![screen shot 2018-05-14 at 2 34 39](https://user-images.githubusercontent.com/5501268/39970015-76864792-571f-11e8-9bf5-41e3991bb034.png)   | Channel Name(`Jobs` in the image)  | 🙆‍♂️ |

### Tasks
- [ ] create `Pined` view
- [ ] ~~create `New messages!` view~~ taken. WIP in https://github.com/withspectrum/spectrum/pull/3152
- [ ] create `Locked` view
- [ ] create `Openchat` view

**Comment by ryota-murakami** [comment]
@mxstbr @brianlovin I think we don't need take care about this issue.
 because mobile `PillOrMessageCount` was implemented already in https://github.com/withspectrum/spectrum/pull/3280.

so can i close this issue?

**Comment by brianlovin** [comment]
I think this can be closed, yup! Thanks for following up :)

**Comment by ryota-murakami** [comment]
@brianlovin Sure, thanks for response:)
