### ISSUE TITLE
[Mobile] Add mobile tracking

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3265]
- [x] Amplitude (Expo has [built-in support for Amplitude](https://docs.expo.io/versions/latest/sdk/amplitude))
  - [x] Make analytics utils (`src/helpers/analytics/`) shared between react native and the web client (#3291)
  - [x] Backfill tracking for existing app code (#3292)
- [ ] Google Analytics (should probably use [this GA + RN module](https://github.com/react-native-community/react-native-google-analytics) which is maintained by the expo team)
  - [ ] Track pageviews in mobile app

**Comment by brianlovin** [comment]
We're no longer actively working on mobile - closing to clean up our issues, and we can search for [mobile] in the future when we get back to this :)
